name: Build package

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Check if version already exists
        run: |
          VERSION=$(grep '^version' pyproject.toml | sed 's/version = //' | tr -d '" ')
          echo "Detected version: $VERSION"
          if git ls-remote --tags origin | grep -q "refs/tags/v$VERSION$"; then
            echo "Version v$VERSION already exists!"
            exit 1
          else
            echo "Version v$VERSION is new."
          fi

      - name: Build the package
        run: python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geoapps-dist
          path: dist/